### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rapilo** [curtbraz/Phishing-API#1]
Hi Curt,

first of all I would like to say that what you created is great. 

I tried to install the on-prem from here, I imported the mysql dbs and copied the files in the root. I'm using WAMP on windows for testing.

I receive the following messages shown in the screenshot

![phishapi1](https://user-images.githubusercontent.com/24817860/48319546-69718c00-e663-11e8-890f-9c4f31ec9a59.png)

Selecting the template it allows you to fill in the parameters but then it fails to create the zip.

Is this to do with rights accessing the DB?

![phishapi2](https://user-images.githubusercontent.com/24817860/48319810-8bb8d900-e666-11e8-8460-801d64ec58be.png)

thanks,

**Comment by curtbraz** [comment]
Hey!  Thanks for the kind words, it's all worth it to me if even one person
gets value out of it!

You can ignore the expected parameters on the main page, that's on me..
I've been meaning to fix that code but it shouldn't really affect anything.

Yes, to your point, I think the issues with the zip not working is likely
due to permissions.  Make sure you chmod the /templates/ dir recursively
and make sure the zip application is actually installed on the host.

Please let me know if that doesn't work and I'll be happy to help
troubleshoot it with you!

Thanks,

**Comment by rapilo** [comment]
Hi Curt,

I just saw in the creationtemplate.php that it uses zip commands under Linux. I actually deployed it on a windows machine which obviously won't work . I will deploy it on a Linux and see how it goes. Your hosted version works good.
I also love the awards and the slackbots, you're a champ!

**Comment by curtbraz** [comment]
Great to hear, thanks again!  I've updated the src so that you won't see those errors either from now on, and made minor changes to the landing page.  Feel free to re-apply that main index.php so you're current and let me know if you run into any other hiccups please!  I'm going to close this comment now.

**Comment by curtbraz** [comment]
Hey!

After looking at the code for you, I'm almost certain it's because your web
service account "www-data?" isn't doesn't have sudoers access.  I'm using
"sudo" during the zip process to ensure there are enough rights to perform
the zip.  Try either removing "sudo" from everywhere it's mentioned on line
92 of /templates/templatecreation.php and try that OR you can add
"www-data" to your /etc/sudoers so it has www-data ALL=(root) NOPASSWD:ALL
in there.

Please let me know either way, if you would!

Thanks,

**Comment by rapilo** [comment]
Hi,

that is what I actually did some time ago, removed the sudo and it worked.

wwwdata had the rights, it was just the sudo. 

I tested the your online version word doc, it doesn't work on word 2016 and 2013, shows some errors.
as per the hosted version, I still had the zip issue, even removing the sudo, but didn't try to add www-data to the sudoes yet, I will try and let you know,

again as always, good work!

thanks,
