### ISSUE TITLE
New site

### ISSUE THREAD

**Issue by Sara123984** [curtbraz/Phishing-API#3]
Could you create a fake site for Amazon with OTP ?

**Comment by curtbraz** [comment]
Hello!

Maybe you can explain the need for this to me.  As I understand it, the only reason someone would want to intercept this password would be in order to intercept a physical delivery of a shipment.  What would the benefit be from a legal phishing campaign?  Perhaps you have a legitimate reason, I just want to be careful not to encourage illegal use of my tool.

That being said, anyone can create a template using my git repository themselves.  Simply clone a site using whatever method you prefer, add relevant documented PHP/HTML tags, and save as "template.php" in the proper directories.

Hope this helps!

**Comment by curtbraz** [comment]
Closing
